### ISSUE TITLE
NetStandard 2.0 Support 

### ISSUE THREAD

**Issue by jakenuts** [TwentyFourMinutes/BackgroundQueue#1]
While I understand maintaining a library can become a hassle, especially if it supports older platforms, from my testing there doesn't appear to be anything in the BackgroundQueue that isn't supported in 2.0 so it might be cool to add that temporarily to the target frameworks. 

Nice work & thanks!

**Comment by TwentyFourMinutes** [comment]
Hey there 👋 From my limited memory I don't see any reason to why this should be an issue either. I'll take a look at it tomorrow.

**Comment by TwentyFourMinutes** [comment]
As of the latest v1.0.0.3 this library now supports .netstandard 2.0. :)
